apiVersion: batch/v1
kind: Job
metadata:
  name: snyk-reconciler
spec:
  template:
    spec:
      serviceAccountName: snyk-reconciler
      volumes:
      - name: snyk-cred-test
        configMap:
          name: snyk-cred-test
      containers:
      - image: a1doll/k8sreconciler:test
        name: snyk-reconciler
        resources: {}
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /tmp/.docker
          name: snyk-cred-test
        securityContext:
          privileged: False
          capabilities:
            add: ["NET_ADMIN","SYS_ADMIN"]
        env:
        - name: APIKEY
          valueFrom:
            secretKeyRef:
              name: snyk-creds
              key: APITOKEN
        - name: ORGID
          valueFrom:
            secretKeyRef:
              name: snyk-creds
              key: ORGID
        - name: SNYKAPIVERSION
          value: "2023-11-06~beta"
        - name:  SNYKDEBUG
          value: "False"
      restartPolicy: Never